---
apiVersion: v1
kind: Service
metadata:
  name: test-jobmanager-ui
spec:
  type: NodePort
  ports:
  - name: ui
    port: 8081
    targetPort: 8081
    nodePort: 32001
  selector:
    app: test
    component: jobmanager