apiVersion: v1
kind: Service
metadata:
  name: test-jobmanager
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 4123
    targetPort: 4123
  - name: blob
    port: 4124
    targetPort: 4124
  - name: ha
    port: 4129
    targetPort: 4129
  - name: ui
    port: 8081
    targetPort: 8081
  selector:
    app: test
    component: jobmanager
