---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-shared-pv-claim
spec:
  storageClassName: glusterfs-storageclass
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 10Gi